"use client";

import React, { useState } from "react";
import { Copy, CheckCircle2, FileText } from "lucide-react";
import type { Passport, VerificationResult } from "@/types";

interface SummaryExportProps {
  passport: Passport;
  result: VerificationResult | null;
}

export default function SummaryExport({ passport, result }: SummaryExportProps) {
  const [copied, setCopied] = useState(false);

  const generateSummary = (): string => {
    const lines: string[] = [];
    lines.push("═══════════════════════════════════════════════════════════════");
    lines.push("              DIGITAL EVIDENCE VERIFICATION SUMMARY           ");
    lines.push("              Generated by ProofIt Evidence Platform          ");
    lines.push("═══════════════════════════════════════════════════════════════");
    lines.push("");
    lines.push(`Case Reference:     ${passport.case_id}`);
    lines.push(`Original Filename:  ${passport.blueprint.original_filename}`);
    lines.push(`File Size:          ${passport.blueprint.total_file_size.toLocaleString()} bytes (${(passport.blueprint.total_file_size / 1024 / 1024).toFixed(2)} MB)`);
    lines.push(`Chunk Size:         ${passport.blueprint.chunk_size_bytes.toLocaleString()} bytes (2 MiB)`);
    lines.push(`Chunk Count:        ${passport.blueprint.chunk_count}`);
    lines.push(`Merkle Root:        ${passport.blueprint.root_fingerprint}`);
    lines.push(`Format Version:     ${passport.format_version}`);
    lines.push("");
    lines.push("───────────────────────────────────────────────────────────────");
    lines.push("  VERIFICATION RESULT                                          ");
    lines.push("───────────────────────────────────────────────────────────────");
    lines.push("");

    if (result) {
      lines.push(`Overall Status:     ${result.overall ? "✓ MATCHES ORIGINAL RECORD" : "✗ DOES NOT MATCH ORIGINAL RECORD"}`);
      lines.push(`Pass 1 (Media):     ${result.pass1 ? "✓ PASSED — Merkle root matches media file" : "✗ FAILED — Media file has been altered"}`);
      lines.push(`Pass 2 (Chain):     ${result.pass2 ? "✓ PASSED — All signatures and chain links valid" : "✗ FAILED — Chain integrity compromised"}`);
    } else {
      lines.push("Verification:       Not performed.");
    }

    lines.push("");
    lines.push("───────────────────────────────────────────────────────────────");
    lines.push("  CHAIN OF CUSTODY                                             ");
    lines.push("───────────────────────────────────────────────────────────────");
    lines.push("");

    passport.history.forEach((entry, i) => {
      lines.push(`  [${entry.index}] ${entry.data.full_name}`);
      lines.push(`      ID:        ${entry.data.id_number}`);
      lines.push(`      Agency:    ${entry.data.agency}`);
      lines.push(`      Timestamp: ${new Date(entry.timestamp).toLocaleString()}`);
      lines.push(`      Note:      "${entry.data.note}"`);
      lines.push(`      Sig:       ${entry.signature.slice(0, 32)}…`);
      if (i < passport.history.length - 1) lines.push("");
    });

    if (passport.blueprint.covered_derivatives && passport.blueprint.covered_derivatives.length > 0) {
      lines.push("");
      lines.push("───────────────────────────────────────────────────────────────");
      lines.push("  DERIVATIVE FILES                                             ");
      lines.push("───────────────────────────────────────────────────────────────");
      lines.push("");

      passport.blueprint.covered_derivatives.forEach((d) => {
        lines.push(`  File:        ${d.filename}`);
        lines.push(`  Fingerprint: ${d.fingerprint}`);
        lines.push(`  Reason:      ${d.reason}`);
        lines.push(`  Linked At:   ${new Date(d.linked_at).toLocaleString()}`);
        lines.push("");
      });
    }

    lines.push("");
    lines.push("───────────────────────────────────────────────────────────────");
    lines.push("  CRYPTOGRAPHIC STANDARDS                                      ");
    lines.push("───────────────────────────────────────────────────────────────");
    lines.push("");
    lines.push("  Hashing:          SHA-256 (NIST FIPS 180-4)");
    lines.push("  Signatures:       ECDSA P-256 (NIST FIPS 186-4)");
    lines.push("  Key Derivation:   PBKDF2-HMAC-SHA256 (NIST SP 800-132)");
    lines.push("  Canonicalization: RFC 8785 JSON Canonicalization Scheme");
    lines.push("  Container:        Store-mode ZIP (0% compression)");
    lines.push("");
    lines.push("═══════════════════════════════════════════════════════════════");
    lines.push(`  Generated: ${new Date().toISOString()}`);
    lines.push("═══════════════════════════════════════════════════════════════");

    return lines.join("\n");
  };

  const handleCopy = async () => {
    const summary = generateSummary();
    await navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div>
      <h3 className="text-xs font-medium uppercase tracking-wider mb-3"
          style={{ color: "var(--color-text-muted)" }}>Verification Summary</h3>
      <button onClick={handleCopy} className="btn btn-ghost w-full justify-center gap-2">
        {copied ? (
          <>
            <CheckCircle2 className="w-4 h-4" style={{ color: "var(--color-verified)" }} />
            <span style={{ color: "var(--color-verified)" }}>Copied to Clipboard</span>
          </>
        ) : (
          <>
            <Copy className="w-4 h-4" />
            <span>Copy Verification Summary to Clipboard</span>
          </>
        )}
      </button>
    </div>
  );
}
